# Build and run stuff. Should find a way to automatically include headers and impl. files...

GNUSTEP_MAKEFILES = /c/GNUstep/GNUstep/System/Library/Makefiles

include $(GNUSTEP_MAKEFILES)/common.make

VERSION = 0.1
PACKAGE_NAME = testapp
TOOL_NAME = TestApp
TestApp_HEADER_FILES = TestApp.h
TestApp_OBJC_FILES = TestApp.m main.m

include $(GNUSTEP_MAKEFILES)/tool.make
