GNUSTEP_MAKEFILES = /c/GNUstep/GNUstep/System/Library/Makefiles

include $(GNUSTEP_MAKEFILES)/common.make

CC = clang
VERSION = 0.1
PACKAGE_NAME = assignment_two_part_two
ADDITIONAL_FLAGS += -fblocks
TOOL_NAME = AssignmentTwoPartTwo
AssignmentTwoPartTwo_HEADER_FILES = $(wildcard *.h)
AssignmentTwoPartTwo_OBJC_FILES = $(wildcard *.m)

include $(GNUSTEP_MAKEFILES)/tool.make
