//
//  main.m
//  Levenshtein
//
//  Created by Emil Klarskov Kristensen on 1/29/13.
//  Copyright (c) 2013 Emil Klarskov Kristensen. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "LevenshteinDistance.h"

int main(int argc, const char * argv[])
{

    @autoreleasepool {
        
        LevenshteinDistance *l = [[LevenshteinDistance alloc] init];
        
        NSString *str1 = @"dkasndjndn3qiirujewfjsimnxvjnxjssssssssssssssssssssssssssssssklkjiweiwuquytuiwehusnjnvnmxbcvnxbcvnmbccccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllhshfjjjijwyrq789yuhjrhjkfhfkjhsjkfhjsdhfjhsdjkfhjhuhwuiyqeiu267819vnbcnmvbdlaldlpwqopiqrouesssssssssklkjiweiwuquytuiwehusnjnvnmxbcvnxbcvnmbccccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllhshfjjjijwyrq789yuhjrhjkfhfkjhsjkfhjsdhfjhsdjkfhjhuhwuiyqeiu267819vnbcnmvbdlaldlpwqopiqrouesssssssssklkjiweiwuquytuiwehusnjnvnmxbcvnxbcvnmbccccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllhshfjjjijwyrq789yuhjrhjkfhfkjhsjkfhjsdhfjhsdjkfhjhuhwuiyqeiu267819vnbcnmvbdlaldlpwqopiqrouesssssssssklkjiweiwuquytuiwehusnjnvnmxbcvnxbcvnmbccccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllhshfjjjijwyrq789yuhjrhjkfhfkjhsjkfhjsdhfjhsdjkfhjhuhwuiyqeiu267819vnbcnmvbdlaldlpwqopiqrouesssssssssklkjiweiwuquytuiwehusnjnvnmxbcvnxbcvnmbccccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllhshfjjjijwyrq789yuhjrhjkfhfkjhsjkfhjsdhfjhsdjkfhjhuhwuiyqeiu267819vnbcnmvbdlaldlpwqopiqrouesssssssssklkjiweiwuquytuiwehusnjnvnmxbcvnxbcvnmbccccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllhshfjjjijwyrq789yuhjrhjkfhfkjhsjkfhjsdhfjhsdjkfhjhuhwuiyqeiu267819vnbcnmvbdlaldlpwqopiqroueiwtgjkjgkshfjhjfkgyfiqyiuijqwhjhqwjdghasgdghajsd";
        
        NSString *str2 = @"dsdu3rhvskdklkalwoi3u8278325jkjbhcgagfhyhfihfhuiehwufhuewhufhuwehuifhuihujcdncxnbvncbvnbnmxvxcbckllwkwqioqioeqirytygbvnckkcmksmcksmclkdmcklsmckmskfghjshfghhjgqueiqweiopqwioeijjfjdskshgaqåiiovnxdnhunrnvhumcfdffffssssxwxwxkwmjsfsgdfgdfggjcnhucmrikohwufhuewhufhuwehuifhuihujcdncxnbvncbvnbnmxvxcbckllwkwqioqioeqirytygbvnckkcmksmcksmclkdmcklsmckmskfghjshfghhjgqueiqweiopqwioeijjfjdskshgaqåiiovnxdnhunrnvhumcfdffffssssxwxwxkwmjsfsgdfgdfhwufhuewhufhuwehuifhuihujcdncxnbvncbvnbnmxvxcbckllwkwqioqioeqirytygbvnckkcmksmcksmclkdmcklsmckmskfghjshfghhjgqueiqweiopqwioeijjfjdskshgaqåiiovnxdnhunrnvhumcfdffffssssxwxwxkwmjsfsgdfgdfggjcnhucmrikohwufhuewhufhuwehuifhuihujcdncxnbvncbvnbnmxvxcbckllwkwqioqioeqirytygbvnckkcmksmcksmclkdmcklsmckmskfghjshfghhjgqueiqweiopqwioeijjfjdskshgaqåiiovnxdnhunrnvhumcfdffffssssxwxwxkwmjshwufhuewhufhuwehuifhuihujcdncxnbvncbvnbnmxvxcbckllwkwqioqioeqirytygbvnckkcmksmcksmclkdmcklsmckmskfghjshfghhjgqueiqweiopqwioeijjfjdskshgaqåiiovnxdnhunrnvhumcfdffffssssxwxwxkwmjsfsgdfgdfggjcnhucmrikofsgdfgdfggjcnhucmrikoggjcnhucmrikohwufhuewhufhuwehuifhuihujcdncxnbvncbvnbnmxvxcbckllwkwqioqioeqirytygbvnckkcmksmcksmclkdmcklsmckmskfghjshfghhjgqueiqweiopqwioeijjfjdskshgaqåiiovnxdnhunrnvhumcfdffffssssxwxwxkwmjsfsgdfgdfggjcnhucmrikohwufhuewhufhuwehuifhuihujcdncxnbvncbvnbnmxvxcbckllwkwqioqioeqirytygbvnckkcmksmcksmclkdmcklsmckmskfghjshfghhjgqueiqweiopqwioeijjfjdskshgaqåiiovnxdnhunrnvhumcfdffffssssxwxwxkwmjsfsgdfgdfggjcnhucmrikohwufhuewhufhuwehuifhuihujcdncxnbvncbvnbnmxvxcbckllwkwqioqioeqirytygbvnckkcmksmcksmclkdmcklsmckmskfghjshfghhjgqueiqweiopqwioeijjfjdskshgaqåiiovnxdnhunrnvhumcfdffffssssxwxwxkwmjsfsgdfgdfggjcnhucmrikohwufhuewhufhuwehuifhuihujcdncxnbvncbvnbnmxvxcbckllwkwqioqioeqirytygbvnckkcmksmcksmclkdmcklsmckmskfghjshfghhjgqueiqweiopqwioeijjfjdskshgaqåiiovnxdnhunrnvhumcfdffffssssxwxwxkwmjsfsgdfgdfggjcnhucmrikohwufhuewhufhuwehuifhuihujcdncxnbvncbvnbnmxvxcbckllwkwqioqioeqirytygbvnckkcmksmcksmclkdmcklsmckmskfghjshfghhjgqueiqweiopqwioeijjfjdskshgaqåiiovnxdnhunrnvhumcfdffffssssxwxwxkwmjsfsgdfgdfggjcnhucmrikoer";
        
        NSInteger dis = [l computeLevenshteinDistanceOf:str1 andString:str2];
        
        NSLog(@"%ld",(long)dis);
    }
    return 0;
}

