include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = Assignment3
Assignment3_HEADER_FILES = Citizen.h NoblePerson.h
Assignment3_OBJC_FILES = Citizen.m NoblePerson.m main.m 

include $(GNUSTEP_MAKEFILES)/tool.make