include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = Assignment2
Assignment2_HEADER_FILES = Citizen.h Child.h Parent.h
Assignment2_OBJC_FILES = Citizen.m Child.m Parent.m main.m 

include $(GNUSTEP_MAKEFILES)/tool.make