include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = Assignment2
Assignment2_HEADER_FILES = Citizen.h NoblePerson.h
Assignment2_OBJC_FILES = Citizen.m NoblePerson.m main.m 

include $(GNUSTEP_MAKEFILES)/tool.make