include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = Assignment4
Assignment4_HEADER_FILES = ClassNoProtocol.h ProtocolOne.h ProtocolBig.h
Assignment4_OBJC_FILES = ClassNoProtocol.m ProtocolOne.m ProtocolBig.m main.m 

include $(GNUSTEP_MAKEFILES)/tool.make