# Build and run stuff. Should find a way to automatically include headers and impl. files...

GNUSTEP_MAKEFILES = /c/GNUstep/GNUstep/System/Library/Makefiles

include $(GNUSTEP_MAKEFILES)/common.make

VERSION = 0.1
PACKAGE_NAME = assignment_two
TOOL_NAME = AssignmentTwo
AssignmentTwo_HEADER_FILES = Citizen.h NoblePerson.h
AssignmentTwo_OBJC_FILES = Citizen.m NoblePerson.m main.m

include $(GNUSTEP_MAKEFILES)/tool.make
